openapi: "3.0.0"
info:
  title: "D&D Teams Bot API"
  version: "1.0.0"

paths:
  /api/messages:
    post:
      summary: "Recibe mensajes de Teams"
      operationId: "src.infrastructure.adapters.rest.teams_adapter.process_message"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: "El mensaje recibido de Teams"
      responses:
        200:
          description: "Mensaje recibido correctamente"
        201:
          description: "Respuesta enviada de forma asíncrona"